In [4]:
# Addition

In [5]:
a=[[1,2,3],[4,5,6]]
b=[[2,4,6],[8,10,12]]

In [6]:
c=[]

for rowA,rowB in zip(a,b):
    
    rowOutput=[rowA[i]+rowB[i] for i in range(3)]
    
    c.append(rowOutput)
    

In [3]:
c

[[3, 6, 9], [12, 15, 18]]

In [7]:
# Subtraction

In [8]:
a=[[1,2,3],[4,5,6]]
b=[[2,4,6],[8,10,12]]

In [9]:
c=[]

for rowA,rowB in zip(a,b):
    
    rowOutput=[rowA[i]-rowB[i] for i in range(3)]
    
    c.append(rowOutput)
    

In [10]:
c

[[-1, -2, -3], [-4, -5, -6]]

In [12]:
# Multiplication-Scalar

In [14]:
a=[[1,2,3],[4,5,6]]
b=2

c=[]

for rowA in a:
    
    c.append([x*b for x in rowA])
   


In [15]:
c

[[2, 4, 6], [8, 10, 12]]

In [16]:
# Multiplication - Matrix

In [38]:
a=np.array([[1,2,3],
   [4,5,6]])

b=np.array([[2,4,6],
   [8,10,12],[1,2,3]])

In [39]:
a@b

array([[ 21,  30,  39],
       [ 54,  78, 102]])

In [19]:
import numpy as np

In [29]:
a=np.array([[1,2,3],
           [4,5,6],
           [4,5,6]])

b=np.array([[ 2,4,6],
            [8,10,12],
            [1,2,3]])

In [30]:
a*b

array([[ 2,  8, 18],
       [32, 50, 72],
       [ 4, 10, 18]])

In [25]:
np.dot(a,b)

array([[ 21,  30,  39],
       [ 54,  78, 102],
       [ 54,  78, 102]])

In [26]:
np.matmul(a,b)

array([[ 21,  30,  39],
       [ 54,  78, 102],
       [ 54,  78, 102]])

In [41]:
# Regression Equation
# y=mx+c